apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: emartapp

resources:
  - ../../base

commonLabels:
  environment: development

patches:
  - path: replicas-patch.yaml
  - path: resource-patch.yaml

images:
  - name: javaapi
    newName: nguyentienuit/emartapp-javaapi
    newTag: latest
  - name: nodeapi
    newName: nguyentienuit/emartapp-nodeapi
    newTag: latest
  - name: frontend
    newName: nguyentienuit/emartapp-frontend
    newTag: latest
