apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: emartapp

resources:
  - ../../base

patches:
  - path: replicas-patch.yaml
  - path: resource-patch.yaml
  - path: labels-patch.yaml

images:
  - name: javaapi
    newTag: latest
  - name: nodeapi
    newTag: latest
  - name: frontend
    newTag: latest 
