apiVersion: apps/v1
kind: Deployment
metadata:
  name: javaapi
  namespace: emartapp
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapi
  namespace: emartapp
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: emartapp
spec:
  replicas: 1 
