apiVersion: apps/v1
kind: Deployment
metadata:
  name: javaapi
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapi
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1 