apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: emartapp
data:
  POSTGRES_DB: emart
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: emartapp
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=  # postgres
  POSTGRES_PASSWORD: cG9zdGdyZXM=  # postgres 