apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - database-config.yaml
  - database-pvc.yaml
  - database-deployment.yaml
  - backend-deployment.yaml
  - frontend-deployment.yaml
  - service.yaml
  - network-policy.yaml
  - pod-security-policy.yaml

commonLabels:
  app.kubernetes.io/part-of: emartapp
  app.kubernetes.io/managed-by: kustomize

images:
  - name: javaapi
    newName: ${DOCKER_REGISTRY}/emartapp-javaapi
    newTag: ${BUILD_NUMBER}
  - name: nodeapi
    newName: ${DOCKER_REGISTRY}/emartapp-nodeapi
    newTag: ${BUILD_NUMBER}
  - name: frontend
    newName: ${DOCKER_REGISTRY}/emartapp-frontend
    newTag: ${BUILD_NUMBER} 